P4FILE=../../p4c/tests/03-SplitEthernetCompact.p4
CONNECTALFLAGS += -D PARSER=SplitEthernetCompact
CONNECTALFLAGS += -D DEPARSER=SplitEthernetCompact
CONNECTALFLAGS += -D MATCHTABLE=SplitEthernetCompact
CONNECTALFLAGS += -D TYPEDEF=SplitEthernetCompact
include ../Makefile.common
