P4FILE=p4src/coordinator.p4
CONNECTALFLAGS += -D PARSER=coordinator
CONNECTALFLAGS += -D DEPARSER=coordinator
CONNECTALFLAGS += -D MATCHTABLE=coordinator
CONNECTALFLAGS += -D TYPEDEF=coordinator
###########################################
# Default Rules
###########################################
include ../Makefile.common
