P4FILE=p4src/acceptor.p4
CONNECTALFLAGS += -D PARSER=Parser
CONNECTALFLAGS += -D DEPARSER=Deparser
CONNECTALFLAGS += -D MATCHTABLE=acceptor
CONNECTALFLAGS += -D TYPEDEF=StructGenerated
###########################################
# Default Rules
###########################################
include ../Makefile.common
