DPL_BENCHMARK=../../submodules/dpl-benchmark/
P4FILE=$(DPL_BENCHMARK)/tcp_diagnosis/p4src/rinc.p4
CONNECTALFLAGS += -D PARSER=rinc
CONNECTALFLAGS += -D DEPARSER=rinc
CONNECTALFLAGS += -D MATCHTABLE=rinc
CONNECTALFLAGS += -D TYPEDEF=rinc
include ../Makefile.common
