P4FILE=../../p4c/tests/07-MultiProtocol.p4
CONNECTALFLAGS += -D PARSER=MultiProtocol
CONNECTALFLAGS += -D DEPARSER=MultiProtocol
CONNECTALFLAGS += -D MATCHTABLE=MultiProtocol
CONNECTALFLAGS += -D TYPEDEF=MultiProtocol
CONNECTALFLAGS += --bscflags="-fdir $(P4FPGADIR)/examples/multiproto/generatedbsv"
include ../Makefile.common
