P4FILE=../../p4c/tests/07-MultiProtocol.p4
CONNECTALFLAGS += -D PARSER=Parser
CONNECTALFLAGS += -D DEPARSER=Deparser
CONNECTALFLAGS += -D MATCHTABLE=MultiProtocol
CONNECTALFLAGS += -D TYPEDEF=StructGenerated
CONNECTALFLAGS += --bscflags="-fdir $(P4FPGADIR)/examples/multiproto/generatedbsv"
include ../Makefile.common
