DPL_BENCHMARK=../../submodules/dpl-benchmark/
P4FILE=$(DPL_BENCHMARK)/rinc/p4src/rinc.p4
CONNECTALFLAGS += -D PARSER=Parser
CONNECTALFLAGS += -D DEPARSER=Deparser
CONNECTALFLAGS += -D MATCHTABLE=rinc
CONNECTALFLAGS += -D TYPEDEF=StructGenerated
include ../Makefile.common
