P4FILE=p4src/coordinator.p4
CONNECTALFLAGS += -D PARSER=Parser
CONNECTALFLAGS += -D DEPARSER=Deparser
CONNECTALFLAGS += -D MATCHTABLE=coordinator
CONNECTALFLAGS += -D TYPEDEF=StructGenerated
###########################################
# Default Rules
###########################################
include ../Makefile.common
