P4FILE=p4src/mdp.p4
CONNECTALFLAGS += --bsvpath=$(CURDIR)/lib
CONNECTALFLAGS += -D PARSER=Parser
CONNECTALFLAGS += -D DEPARSER=Deparser
CONNECTALFLAGS += -D MATCHTABLE=Control
CONNECTALFLAGS += -D TYPEDEF=StructDefines
CONNECTALFLAGS += --bsvpath=generatedbsv

include ../Makefile.common
