P4FILE=../../p4c/tests/07-MultiProtocol.p4
CONNECTALFLAGS += -D PARSER=MultiProtocol
CONNECTALFLAGS += -D DEPARSER=MultiProtocol
CONNECTALFLAGS += -D MATCHTABLE=MultiProtocol
CONNECTALFLAGS += -D TYPEDEF=MultiProtocol
include ../Makefile.common
