P4FILE=p4src/acceptor.p4
CONNECTALFLAGS += -D PARSER=acceptor_ref
CONNECTALFLAGS += -D DEPARSER=acceptor
CONNECTALFLAGS += -D MATCHTABLE=acceptor
CONNECTALFLAGS += -D TYPEDEF=acceptor
###########################################
# Default Rules
###########################################
include ../Makefile.common
