DPL_BENCHMARK=../../submodules/dpl-benchmark/
P4FILE=$(DPL_BENCHMARK)/tcp_options_parser/p4src/main.p4
CONNECTALFLAGS += -D PARSER=main
CONNECTALFLAGS += -D DEPARSER=main
CONNECTALFLAGS += -D MATCHTABLE=main
CONNECTALFLAGS += -D TYPEDEF=main
include ../Makefile.common
