DPL_BENCHMARK=../../submodules/dpl-benchmark/
P4FILE=$(DPL_BENCHMARK)/nat/p4src/nat.p4
CONNECTALFLAGS += -D PARSER=nat
CONNECTALFLAGS += -D DEPARSER=nat
CONNECTALFLAGS += -D MATCHTABLE=nat
CONNECTALFLAGS += -D TYPEDEF=nat
include ../Makefile.common
