DPL_BENCHMARK=../../submodules/dpl-benchmark/
P4FILE=$(DPL_BENCHMARK)/source_routing/p4src/source_routing.p4
CONNECTALFLAGS += -D PARSER=source_routing
CONNECTALFLAGS += -D DEPARSER=source_routing
CONNECTALFLAGS += -D MATCHTABLE=source_routing
CONNECTALFLAGS += -D TYPEDEF=source_routing
include ../Makefile.common
